# Generated by Django 5.2.9 on 2026-01-10 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_time'),
        ('doctor', '0007_alter_review_unique_together'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor', 'time', 'date'), name='unique_patient_doctor_time_date'),
        ),
    ]
