# Generated by Django 5.2.9 on 2026-01-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_remove_appointment_unique_patient_doctor_time_date_and_more'),
        ('doctor', '0007_alter_review_unique_together'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_patient_doctor_time',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor', 'time', 'date'), name='unique_patient_doctor_time_date'),
        ),
    ]
