# Generated by Django 5.2.9 on 2026-01-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='desigantion',
            new_name='designation',
        ),
    ]
