# Generated by Django 5.2.9 on 2026-01-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='meet_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
