# Generated by Django 5.2.9 on 2026-01-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_alter_doctor_meet_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(upload_to='doctor/images/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='meet_link',
            field=models.CharField(default='http://meet.com', max_length=100),
        ),
    ]
